export const keywords: Array<string> = [
  'baguette',
  'cigarette',
  'clope',
  'malbac',
  'pinard',
  'saucisson',
  'vin rouge',
  'hon hon hon',
  'bouillabaisse',
  'croissant',
  'reblochon',
  'tour eiffel',
  'ennui',
  'fin de siècle',
  'brigitte bardot',
  'arc de triomphe',
  'paris',
  'paname',
  'sacrebleu',
  'parbleu',
  'putain',
  'fait chier',
  'merde',
  'euh',
  'chardonnay',
  'pinot noir',
  'grève',
  'CGT',
  'merguez',
  'pastis',
  'liberté égalité fraternité',
  'gilet jaunes',
  'bourguignon',
  'bordeaux',
  'brie',
  'camembert',
  "bleu d'auvergne",
  'mont saint michel',
  'normandie',
  'côtes du rhône',
  'saperlipopette',
  'steak frites',
  'sauce au poivre',
  'coq au vin',
  'ravaillac',
  'louis XVI',
  'napoléon',
  'paname',
  'bouillabaisse',
  'reblochon',
  'tartiflette',
];

export default keywords;
